[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = ''' ! has('nvim') '''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = ''' ! has('nvim') '''

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
       " パワーライン
       let g:airline_powerline_fonts = 1
       " カラーテーマ
       let g:airline_theme = 'minimalist'
       " タブバー
       let g:airline#extensions#tabline#enabled = 1
       " （タブが一個の場合）バッファのリストをタブラインに表示する機能をオフ
       let g:airline#extensions#tabline#show_buffers = 0
       " タブ文字列
       let g:airline#extensions#tabline#formatter = 'unique_tail'
       " タブとバッファ表示
"      let g:airline#extensions#tabline#show_splits = 1
"      let g:airline#extensions#tabline#show_buffers = 1
"      let g:airline#extensions#tabline#switch_buffers_and_tabs = 1
       " ale
       let g:airline#extensions#ale#enabled = 1

       " 選択行列の表示をカスタム(デフォルトだと長くて横幅を圧迫するので最小限に)
"      let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
'''
 
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
	if has('nvim')
		let g:tagbar_iconchars = ['+', '-']
	endif
	let g:tagbar_sort = 0
	nnoremap <silent> <Leader>f :<C-u>TagbarToggle<CR>
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	nnoremap <silent> <Leader>n :<C-u>NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/vim-vcs'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
	nmap <Leader>c <Plug>(caw:zeropos:comment)
	vmap <Leader>c <Plug>(caw:zeropos:comment)
	nmap <Leader>C <Plug>(caw:zeropos:uncomment)
	vmap <Leader>C <Plug>(caw:zeropos:uncomment)
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	let g:quickrun_config = {'*': {'split': ''}}
'''
