[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = ''' ! has('nvim') '''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = ''' ! has('nvim') '''

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	if has('nvim')
		source ~/.vim/rc/plugins/lightline.rc.vim
	else
		source ~/.vim/rc/plugins/lightline_powerline.rc.vim
	endif
'''

# [[plugins]]
# repo = 'vim-airline/vim-airline'
# hook_add = '''
# 	if ! has('nvim')
# 		let g:airline_powerline_fonts = 1
# 	endif
# '''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
	if has('nvim')
		let g:tagbar_iconchars = ['+', '-']
	endif
	let g:tagbar_sort = 0

	nnoremap <silent> <Leader>f :<C-u>TagbarToggle<CR>
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	nnoremap <silent> <Leader>n :<C-u>NERDTreeToggle<CR>
'''
# TODO
# [[plugins]]
# repo = 'Shougo/vimfiler.vim'
# [[plugins]]
# repo = 'Shougo/defx.vim'

[[plugins]]
repo = 'Shougo/vim-vcs'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = '''
# 	let g:indent_guides_enable_on_vim_startup = 1
# '''
#  vim-indent-guidesから乗り換え
#  ようかと思ったけどsetでできるでしょって言われた。
# [[plugins]]
# repo = 'Yggdroot/indentLine'


[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
	nmap <Leader>c <Plug>(caw:zeropos:comment)
	vmap <Leader>c <Plug>(caw:zeropos:comment)
	nmap <Leader>C <Plug>(caw:zeropos:uncomment)
	vmap <Leader>C <Plug>(caw:zeropos:uncomment)
'''

[[plugins]]
repo = 'KabbAmine/zeavim.vim'
hook_add = '''
source ~/.vim/rc/plugins/zeavim.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'yuratomo/w3m.vim'

# TODO:neco

